Repository NMNB-Team/NMNB-Backend, pull requests merged in 2025-05, with the labels that each got.

#44 [refactor] S3 관련 설정 common 모듈로 이동
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/domain/CustomUserDetails.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/generator/AuthUserArgumentResolver.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/generator/annotation/AuthUser.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/service/AuthServiceImpl.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/test/TestAuthService.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/utils/JwtTokenProvider.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/config/S3Properties.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/config/WebConfig.kt
  nmnb-application/src/test/kotlin/nmnb/application/domain/user/service/UserServiceImplTest.kt
  nmnb-application/src/test/kotlin/nmnb/application/global/auth/service/AuthServiceIntegrationTest.kt
  nmnb-common/build.gradle.kts
  nmnb-common/src/main/kotlin/nmnb/common/config/S3Config.kt
  nmnb-common/src/main/kotlin/nmnb/common/properties/S3Properties.kt
  nmnb-domain/src/main/kotlin/nmnb/domain/user/User.kt
  nmnb-domain/src/main/kotlin/nmnb/domain/user/generator/CustomIdGenerator.kt
  nmnb-r2dbc/src/main/kotlin/nmnb/r2dbc/user/R2dbcUser.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/auth/utils/JwtTokenProvider.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/common/service/S3Service.kt
Labels: refactor

#46 [chore] 토큰 claims 변경에 따른 메서드 네이밍 수정 적용 및 패키지 이동에 따른 import 경로 정리
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/service/RefreshTokenService.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/auth/utils/JWTFilter.kt
  nmnb-webflux/src/test/kotlin/nmnb/webflux/global/common/service/S3ServiceTest.kt
Labels: chore

#47 [feat] @AuthUser 어노테이션을 통한 로그인 사용자 주입 기능 구현 및 리팩토링
  nmnb-application/src/main/kotlin/nmnb/application/domain/like/controller/LikeController.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/like/controller/dto/request/PostLikeRequest.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/like/service/dto/request/PostLikeServiceRequest.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/post/controller/PostController.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/user/controller/UserController.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/user/controller/dto/request/UserPetRegistrationRequest.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/user/service/UserService.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/user/service/UserServiceImpl.kt
  nmnb-application/src/main/kotlin/nmnb/application/domain/user/service/dto/request/UserPetRegistrationServiceRequest.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/controller/AuthController.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/generator/AuthUserArgumentResolver.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/generator/annotation/TokenApiResponse.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/service/AuthServiceImpl.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/utils/JWTFilter.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/config/SecurityConfig.kt
  nmnb-application/src/test/kotlin/nmnb/application/ControllerTestSupport.kt
  nmnb-application/src/test/kotlin/nmnb/application/TestApplication.kt
  nmnb-application/src/test/kotlin/nmnb/application/domain/like/controller/LikeControllerTest.kt
  nmnb-application/src/test/kotlin/nmnb/application/domain/like/service/LikeServiceImplTest.kt
  nmnb-application/src/test/kotlin/nmnb/application/domain/user/controller/UserControllerTest.kt
  nmnb-application/src/test/kotlin/nmnb/application/domain/user/service/UserServiceImplTest.kt
  nmnb-application/src/test/kotlin/nmnb/application/global/auth/controller/AuthControllerTest.kt
  nmnb-webflux/src/test/kotlin/nmnb/webflux/TestApplication.kt
Labels: feat, refactor
