Repository NMNB-Team/NMNB-Backend, pull requests merged in 2025-06, with the labels that each got.

#54 [feat] 영상 업로드 시 썸네일 생성 및 저장 로직 구현
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/service/AuthServiceImpl.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/service/RefreshTokenService.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/auth/test/TestAuthService.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/config/SecurityConfig.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/infrastructure/external/oauth/BaseOAuthClient.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/infrastructure/external/oauth/KakaoOAuthClient.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/infrastructure/external/oauth/OAuthClient.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/infrastructure/external/oauth/OAuthClientComposite.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/infrastructure/security/JWTFilter.kt
  nmnb-application/src/main/kotlin/nmnb/application/global/infrastructure/security/JwtTokenProvider.kt
  nmnb-application/src/test/kotlin/nmnb/application/ControllerTestSupport.kt
  nmnb-application/src/test/kotlin/nmnb/application/global/auth/service/AuthServiceImplTest.kt
  nmnb-application/src/test/kotlin/nmnb/application/global/auth/service/AuthServiceIntegrationTest.kt
  nmnb-common/src/main/kotlin/nmnb/common/response/status/ErrorStatus.kt
  nmnb-r2dbc/src/main/kotlin/nmnb/r2dbc/post/R2dbcPost.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/domain/post/service/PostUploadServiceImpl.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/common/service/S3Service.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/config/SecurityConfig.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/external/ffmpeg/FfmpegService.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/external/redis/ThumbnailJobProducer.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/external/redis/ThumbnailWorker.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/external/redis/dto/ThumbnailJobPayload.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/external/s3/S3Service.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/security/JWTFilter.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/security/JwtTokenProvider.kt
  nmnb-webflux/src/test/kotlin/nmnb/webflux/ControllerTestSupport.kt
  nmnb-webflux/src/test/kotlin/nmnb/webflux/domain/post/service/PostUploadServiceImplTest.kt
  nmnb-webflux/src/test/kotlin/nmnb/webflux/global/infrastructure/external/ffmpeg/FfmpegServiceTest.kt
  nmnb-webflux/src/test/kotlin/nmnb/webflux/global/infrastructure/external/s3/S3ServiceTest.kt
  nmnb-webflux/src/test/resources/sample-video.mp4
Labels: feat

#55 [fix] 비디오 다운로드 경로 버그 수정 및 스웨거 문서 개선
  nmnb-common/src/main/kotlin/nmnb/common/response/status/ErrorStatus.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/domain/post/controller/PostController.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/auth/generator/annotation/TokenApiResponse.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/infrastructure/external/s3/S3Service.kt
Labels: fix, docs

#61 [fix] 경로 netty 표시해 프록시 적용되도록 수정
  nmnb-webflux/src/main/kotlin/nmnb/webflux/domain/post/controller/PostController.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/config/SecurityConfig.kt
Labels: fix

#59 [hotfix] 이미지 pull 방식으로 변경하여 이전 이미지가 build되는 문제 해결
  docker-compose.override.yml
  nmnb-webflux/src/main/kotlin/nmnb/webflux/domain/post/controller/PostController.kt
  nmnb-webflux/src/main/kotlin/nmnb/webflux/global/config/SecurityConfig.kt
  scripts/dev-deploy.sh
  scripts/prod-deploy.sh
Labels: fix
